[package]
name = "sentry-integration"
version = "0.1.0"
description = "Sentry-related methods"
authors = ["David Sferruzza <david.sferruzza@gmail.com>"]
edition = "2021"
license = "SSPL-1.0"

[dependencies]
env_logger = "0.11.3"
log = "0.4.21"
sentry = { version = "0.32.2", default-features = false, features = ["backtrace", "contexts", "panic", "reqwest", "rustls", "log", "debug-logs", "anyhow"] }
